### ISSUE TITLE
Can't use yielding dependecy with its own dependencies

### ISSUE THREAD

**Issue by alamaison** [Lancetnik/FastDepends#179]
The following code works fine:
```python
async def dep_c():
    yield ["foo"]


@inject
async def dep_b(c=Depends(dep_c)):
    return c


@inject
async def a(b=Depends(dep_b)):
    return b[0]


async def test_deps():
    r = await a()
    assert r == "foo"
```
The yielding dependency `dep_c` is correctly converted to the concrete value `["foo"]` inside `dep_b`.  But if `dep_b` is itself a yielding function it fails because the depended value is still a generator - it hasn't been resolved
```python
async def dep_c():
    yield ["foo"]


@inject
async def dep_b(c=Depends(dep_c)):
    yield c


@inject
async def a(b=Depends(dep_b)):
    return b[0]


async def test_deps():
    r = await a()
    assert r == "foo"
```
```
 TypeError: 'solve_async_gen' object is not subscriptable
```

This is different from[ the behaviour in FastAPI](https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/#sub-dependencies-with-yield).

**Comment by alamaison** [comment]
You mean this issue is fixed in version 3.0.0a5?  What is FastStream?

**Comment by Lancetnik** [comment]
> You mean this issue is fixed in version 3.0.0a5? What is FastStream?

I am not sure if the problem was fixed, but the main branch has been frozen until the 3.0.0 release. The latest FastDepends version on PyPI is 3.0.0a5. You can install it from there.

FastStream is a framework that I have created and FastDepends is a tool that I use for it. You can find it on GitHub at https://github.com/ag2ai/faststream.

**Comment by alamaison** [comment]
Thanks for the new build.

I'm afraid v3 is even worse.  Now both examples fail.  The returning example like this:
```
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/use.py:181: in injected_wrapper
    return await real_model.asolve(  # type: ignore[no-any-return]
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/core/model.py:308: in asolve
    kwargs[dep_arg] = await self.dependency_provider.get_dependant(dep_key).asolve(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fast_depends.dependencies.provider.Provider object at 0x7ee0ba1f38c0>
key = <function dep_b at 0x7ee0b99b5e40>

    def get_dependant(self, key: Key) -> "CallModel":
>       return self.overrides.get(key) or self.dependencies[key]
E       KeyError: <function dep_b at 0x7ee0b99b5e40>

/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/dependencies/provider.py:37: KeyError
```
and the yielding case like this:
```
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/use.py:181: in injected_wrapper
    return await real_model.asolve(  # type: ignore[no-any-return]
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/core/model.py:308: in asolve
    kwargs[dep_arg] = await self.dependency_provider.get_dependant(dep_key).asolve(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fast_depends.dependencies.provider.Provider object at 0x70ee233eb4d0>
key = functools.partial(<class 'fast_depends.use.solve_async_gen'>, <fast_depends.core.model.CallModel object at 0x70ee22bade40>)

    def get_dependant(self, key: Key) -> "CallModel":
>       return self.overrides.get(key) or self.dependencies[key]
E       KeyError: functools.partial(<class 'fast_depends.use.solve_async_gen'>, <fast_depends.core.model.CallModel object at 0x70ee22bade40>)

/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/dependencies/provider.py:37: KeyError
```

**Comment by Lancetnik** [comment]
@alamaison anyway, I fixed the problem in `3.0.0a7`

**Comment by alamaison** [comment]
Thanks for the fix @Lancetnik.  Unfortunately both cases still fail for me.  If I nest the functions inside the test method, like you do in 7f67de0, the tests pass.  But if the functions are top-level functions, like in my original examples, the test fails with:
```
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/use.py:181: in injected_wrapper
    return await real_model.asolve(  # type: ignore[no-any-return]
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/core/model.py:308: in asolve
    kwargs[dep_arg] = await self.dependency_provider.get_dependant(dep_key).asolve(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fast_depends.dependencies.provider.Provider object at 0x7443f86df4d0>, key = <function dep_b at 0x7443f3ea1e40>

    def get_dependant(self, key: Key) -> "CallModel":
>       return self.overrides.get(key) or self.dependencies[key]
E       KeyError: <function dep_b at 0x7443f3ea1e40>

/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/dependencies/provider.py:37: KeyError
```

**Comment by Lancetnik** [comment]
@alamaison I am not sure what are you talking about. Both your examples are works fine in the branch. I just copied them to test.

Anyway, I shouldn't use decorated by `@inject` functions as a Dependency – it's just an incorrect usage

**Comment by Lancetnik** [comment]
Here is my current tests:

```python
import pytest
from fast_depends import inject, Depends

@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"

async def dep_c():
    yield ["foo"]

@inject
async def dep_b(c=Depends(dep_c)):
    yield c

@inject
async def a(b=Depends(dep_b)):
    return b[0]

@pytest.mark.anyio
async def test_deps():
    r = await a()
    assert r == "foo"
```

And

```python
import pytest
from fast_depends import inject, Depends

@pytest.fixture
def anyio_backend() -> str:
    return "asyncio"

async def dep_c():
    yield ["foo"]

@inject
async def dep_b(c=Depends(dep_c)):
    return c

@inject
async def a(b=Depends(dep_b)):
    return b[0]

@pytest.mark.anyio
async def test_deps():
    r = await a()
    assert r == "foo"
```

Both works fine

**Comment by alamaison** [comment]
Interesting.  When I strip everything else out of my test suite it works fine as you say.  But when I add a fixture to clear overridden dependencies (as in the docs), `test_deps` fails if any other test uses that fixture.  I.e. this fails:
```
import pytest
from fast_depends import Depends, dependency_provider, inject

@pytest.fixture
def dependencies():
    yield dependency_provider
    dependency_provider.clear()

async def test_stub(dependencies):
    assert True

async def dep_c():
    yield ["foo"]

@inject
async def dep_b(c=Depends(dep_c)):
    return c

@inject
async def a(b=Depends(dep_b)):
    return b[0]

async def test_deps():
    r = await a()
    assert r == "foo"
```
with this error
```
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/use.py:181: in injected_wrapper
    return await real_model.asolve(  # type: ignore[no-any-return]
/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/core/model.py:308: in asolve
    kwargs[dep_arg] = await self.dependency_provider.get_dependant(dep_key).asolve(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fast_depends.dependencies.provider.Provider object at 0x7155b10ff0e0>, key = <function dep_b at 0x7155b0fa9b20>

    def get_dependant(self, key: Key) -> "CallModel":
>       return self.overrides.get(key) or self.dependencies[key]
E       KeyError: <function dep_b at 0x7155b0fa9b20>

/home/alex/.cache/pypoetry/virtualenvs/proj-rtt0W6uO-py3.13/lib/python3.13/site-packages/fast_depends/dependencies/provider.py:37: KeyError
```

> Anyway, I shouldn't use decorated by @inject functions as a Dependency – it's just an incorrect usage

I don't think I understand this.  An @inject-ed function should work just like a normal function.  In FastAPI, [sub-dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/sub-dependencies/) are explicitly a features of the dependency injection.

**Comment by Lancetnik** [comment]
> I don't think I understand this. An @inject-ed function should work just like a normal function. In FastAPI, [sub-dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/sub-dependencies/) are explicitly a features of the dependency injection.

Our `@inject` decorator is the same thing with FastAPIs' `@app.get / post / etc`. You couldn't use another endpoint as a dependency, so u couldn't use already decorated function as a dependency as well. Just remove `@inject` decorator on nested depenecny and all should works fine

```python
async def dep_c():
    yield ["foo"]

# @inject  # incorrect usage
async def dep_b(c=Depends(dep_c)):
    yield c

@inject
async def a(b=Depends(dep_b)):
    return b[0]

async def test_deps():
    r = await a()
    assert r == "foo"
```

**Comment by Lancetnik** [comment]
The thing you try to do is equal to

```python
async def dep_c():
    yield ["foo"]

@app.get("/b")
async def dep_b(c=Depends(dep_c)):
    yield c

@app.get("/a")
async def a(b=Depends(dep_b)):
    return b[0]
```

**Comment by alamaison** [comment]
Oh interesting.  That equivalence between `@inject` and an endpoint wasn't clear to me.  I'm still finding that it doesn't work with `@inject` removed when I also have the dependency-clearing fixture on another test in the same suite

**Comment by Lancetnik** [comment]
@alamaison just do not clear dependencies. Please, override them by context manager
`dependency_provider.clear()` drops the dependency tree we built and FastDepends just can't solve anything

**Comment by alamaison** [comment]
Thanks that worked!
